"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module

if TYPE_CHECKING:
    from .apierror import APIError
    from .badrequest_error import BadRequestError, BadRequestErrorData
    from .dbrsdkerror import DbrsdkError
    from .httpvalidationerror import HTTPValidationError, HTTPValidationErrorData
    from .no_response_error import NoResponseError
    from .notfound_error import NotFoundError, NotFoundErrorData
    from .ratelimited_error import RateLimitedError, RateLimitedErrorData
    from .responsevalidationerror import ResponseValidationError
    from .unauthorized_error import UnauthorizedError, UnauthorizedErrorData

__all__ = [
    "APIError",
    "BadRequestError",
    "BadRequestErrorData",
    "DbrsdkError",
    "HTTPValidationError",
    "HTTPValidationErrorData",
    "NoResponseError",
    "NotFoundError",
    "NotFoundErrorData",
    "RateLimitedError",
    "RateLimitedErrorData",
    "ResponseValidationError",
    "UnauthorizedError",
    "UnauthorizedErrorData",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "BadRequestError": ".badrequest_error",
    "BadRequestErrorData": ".badrequest_error",
    "DbrsdkError": ".dbrsdkerror",
    "HTTPValidationError": ".httpvalidationerror",
    "HTTPValidationErrorData": ".httpvalidationerror",
    "NoResponseError": ".no_response_error",
    "NotFoundError": ".notfound_error",
    "NotFoundErrorData": ".notfound_error",
    "RateLimitedError": ".ratelimited_error",
    "RateLimitedErrorData": ".ratelimited_error",
    "ResponseValidationError": ".responsevalidationerror",
    "UnauthorizedError": ".unauthorized_error",
    "UnauthorizedErrorData": ".unauthorized_error",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)
