"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.errors import DbrsdkError
from dbrsdk.types import BaseModel
import httpx
import pydantic
from typing import Any, Dict, Optional
from typing_extensions import Annotated


class UnauthorizedErrorData(BaseModel):
    message: Optional[str] = None

    additional_properties: Annotated[
        Optional[Dict[str, Any]], pydantic.Field(exclude=True)
    ] = None


class UnauthorizedError(DbrsdkError):
    r"""Permission denied or not authenticated"""

    data: UnauthorizedErrorData

    def __init__(
        self,
        data: UnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
