"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module

if TYPE_CHECKING:
    from .advance_time_unit_api_v1_system_advance_time_unit_postop import (
        AdvanceTimeUnitAPIV1SystemAdvanceTimeUnitPostRequest,
        AdvanceTimeUnitAPIV1SystemAdvanceTimeUnitPostRequestTypedDict,
    )
    from .advancetimeresponse import AdvanceTimeResponse, AdvanceTimeResponseTypedDict
    from .boardanalytics import BoardAnalytics, BoardAnalyticsTypedDict
    from .delete_schedule_api_v1_schedules_schedule_id_deleteop import (
        DeleteScheduleAPIV1SchedulesScheduleIDDeleteRequest,
        DeleteScheduleAPIV1SchedulesScheduleIDDeleteRequestTypedDict,
    )
    from .delete_work_item_api_v1_workitems_work_item_id_deleteop import (
        DeleteWorkItemAPIV1WorkitemsWorkItemIDDeleteRequest,
        DeleteWorkItemAPIV1WorkitemsWorkItemIDDeleteRequestTypedDict,
    )
    from .get_board_analytics_api_v1_schedules_board_board_config_id_analytics_getop import (
        GetBoardAnalyticsAPIV1SchedulesBoardBoardConfigIDAnalyticsGetRequest,
        GetBoardAnalyticsAPIV1SchedulesBoardBoardConfigIDAnalyticsGetRequestTypedDict,
    )
    from .get_schedule_analytics_api_v1_schedules_schedule_id_analytics_getop import (
        GetScheduleAnalyticsAPIV1SchedulesScheduleIDAnalyticsGetRequest,
        GetScheduleAnalyticsAPIV1SchedulesScheduleIDAnalyticsGetRequestTypedDict,
    )
    from .get_schedule_api_v1_schedules_schedule_id_getop import (
        GetScheduleAPIV1SchedulesScheduleIDGetRequest,
        GetScheduleAPIV1SchedulesScheduleIDGetRequestTypedDict,
    )
    from .get_schedules_api_v1_schedules_getop import (
        GetSchedulesAPIV1SchedulesGetRequest,
        GetSchedulesAPIV1SchedulesGetRequestTypedDict,
    )
    from .get_work_item_api_v1_workitems_work_item_id_getop import (
        GetWorkItemAPIV1WorkitemsWorkItemIDGetRequest,
        GetWorkItemAPIV1WorkitemsWorkItemIDGetRequestTypedDict,
    )
    from .get_work_items_api_v1_workitems_getop import (
        GetWorkItemsAPIV1WorkitemsGetRequest,
        GetWorkItemsAPIV1WorkitemsGetRequestTypedDict,
    )
    from .loginrequest import LoginRequest, LoginRequestTypedDict
    from .loginresponse import LoginResponse, LoginResponseTypedDict
    from .scheduleanalytics import ScheduleAnalytics, ScheduleAnalyticsTypedDict
    from .schedulecreate import ScheduleCreate, ScheduleCreateTypedDict
    from .scheduleresponse import ScheduleResponse, ScheduleResponseTypedDict
    from .scheduleupdate import ScheduleUpdate, ScheduleUpdateTypedDict
    from .security import Security, SecurityTypedDict
    from .set_system_time_api_v1_system_time_postop import (
        SetSystemTimeAPIV1SystemTimePostRequest,
        SetSystemTimeAPIV1SystemTimePostRequestTypedDict,
    )
    from .taskcreate import TaskCreate, TaskCreateTypedDict
    from .taskresponse import TaskResponse, TaskResponseTypedDict
    from .taskupdate import TaskUpdate, TaskUpdateTypedDict
    from .update_schedule_api_v1_schedules_schedule_id_putop import (
        UpdateScheduleAPIV1SchedulesScheduleIDPutRequest,
        UpdateScheduleAPIV1SchedulesScheduleIDPutRequestTypedDict,
    )
    from .update_work_item_api_v1_workitems_work_item_id_putop import (
        UpdateWorkItemAPIV1WorkitemsWorkItemIDPutRequest,
        UpdateWorkItemAPIV1WorkitemsWorkItemIDPutRequestTypedDict,
    )
    from .update_work_item_task_api_v1_workitems_work_item_id_tasks_task_id_putop import (
        UpdateWorkItemTaskAPIV1WorkitemsWorkItemIDTasksTaskIDPutRequest,
        UpdateWorkItemTaskAPIV1WorkitemsWorkItemIDTasksTaskIDPutRequestTypedDict,
    )
    from .userinfo import UserInfo, UserInfoTypedDict
    from .validationerror import (
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )
    from .workitemcreate import WorkItemCreate, WorkItemCreateTypedDict
    from .workitemresponse import WorkItemResponse, WorkItemResponseTypedDict
    from .workitemupdate import WorkItemUpdate, WorkItemUpdateTypedDict

__all__ = [
    "AdvanceTimeResponse",
    "AdvanceTimeResponseTypedDict",
    "AdvanceTimeUnitAPIV1SystemAdvanceTimeUnitPostRequest",
    "AdvanceTimeUnitAPIV1SystemAdvanceTimeUnitPostRequestTypedDict",
    "BoardAnalytics",
    "BoardAnalyticsTypedDict",
    "DeleteScheduleAPIV1SchedulesScheduleIDDeleteRequest",
    "DeleteScheduleAPIV1SchedulesScheduleIDDeleteRequestTypedDict",
    "DeleteWorkItemAPIV1WorkitemsWorkItemIDDeleteRequest",
    "DeleteWorkItemAPIV1WorkitemsWorkItemIDDeleteRequestTypedDict",
    "GetBoardAnalyticsAPIV1SchedulesBoardBoardConfigIDAnalyticsGetRequest",
    "GetBoardAnalyticsAPIV1SchedulesBoardBoardConfigIDAnalyticsGetRequestTypedDict",
    "GetScheduleAPIV1SchedulesScheduleIDGetRequest",
    "GetScheduleAPIV1SchedulesScheduleIDGetRequestTypedDict",
    "GetScheduleAnalyticsAPIV1SchedulesScheduleIDAnalyticsGetRequest",
    "GetScheduleAnalyticsAPIV1SchedulesScheduleIDAnalyticsGetRequestTypedDict",
    "GetSchedulesAPIV1SchedulesGetRequest",
    "GetSchedulesAPIV1SchedulesGetRequestTypedDict",
    "GetWorkItemAPIV1WorkitemsWorkItemIDGetRequest",
    "GetWorkItemAPIV1WorkitemsWorkItemIDGetRequestTypedDict",
    "GetWorkItemsAPIV1WorkitemsGetRequest",
    "GetWorkItemsAPIV1WorkitemsGetRequestTypedDict",
    "Loc",
    "LocTypedDict",
    "LoginRequest",
    "LoginRequestTypedDict",
    "LoginResponse",
    "LoginResponseTypedDict",
    "ScheduleAnalytics",
    "ScheduleAnalyticsTypedDict",
    "ScheduleCreate",
    "ScheduleCreateTypedDict",
    "ScheduleResponse",
    "ScheduleResponseTypedDict",
    "ScheduleUpdate",
    "ScheduleUpdateTypedDict",
    "Security",
    "SecurityTypedDict",
    "SetSystemTimeAPIV1SystemTimePostRequest",
    "SetSystemTimeAPIV1SystemTimePostRequestTypedDict",
    "TaskCreate",
    "TaskCreateTypedDict",
    "TaskResponse",
    "TaskResponseTypedDict",
    "TaskUpdate",
    "TaskUpdateTypedDict",
    "UpdateScheduleAPIV1SchedulesScheduleIDPutRequest",
    "UpdateScheduleAPIV1SchedulesScheduleIDPutRequestTypedDict",
    "UpdateWorkItemAPIV1WorkitemsWorkItemIDPutRequest",
    "UpdateWorkItemAPIV1WorkitemsWorkItemIDPutRequestTypedDict",
    "UpdateWorkItemTaskAPIV1WorkitemsWorkItemIDTasksTaskIDPutRequest",
    "UpdateWorkItemTaskAPIV1WorkitemsWorkItemIDTasksTaskIDPutRequestTypedDict",
    "UserInfo",
    "UserInfoTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
    "WorkItemCreate",
    "WorkItemCreateTypedDict",
    "WorkItemResponse",
    "WorkItemResponseTypedDict",
    "WorkItemUpdate",
    "WorkItemUpdateTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AdvanceTimeUnitAPIV1SystemAdvanceTimeUnitPostRequest": ".advance_time_unit_api_v1_system_advance_time_unit_postop",
    "AdvanceTimeUnitAPIV1SystemAdvanceTimeUnitPostRequestTypedDict": ".advance_time_unit_api_v1_system_advance_time_unit_postop",
    "AdvanceTimeResponse": ".advancetimeresponse",
    "AdvanceTimeResponseTypedDict": ".advancetimeresponse",
    "BoardAnalytics": ".boardanalytics",
    "BoardAnalyticsTypedDict": ".boardanalytics",
    "DeleteScheduleAPIV1SchedulesScheduleIDDeleteRequest": ".delete_schedule_api_v1_schedules_schedule_id_deleteop",
    "DeleteScheduleAPIV1SchedulesScheduleIDDeleteRequestTypedDict": ".delete_schedule_api_v1_schedules_schedule_id_deleteop",
    "DeleteWorkItemAPIV1WorkitemsWorkItemIDDeleteRequest": ".delete_work_item_api_v1_workitems_work_item_id_deleteop",
    "DeleteWorkItemAPIV1WorkitemsWorkItemIDDeleteRequestTypedDict": ".delete_work_item_api_v1_workitems_work_item_id_deleteop",
    "GetBoardAnalyticsAPIV1SchedulesBoardBoardConfigIDAnalyticsGetRequest": ".get_board_analytics_api_v1_schedules_board_board_config_id_analytics_getop",
    "GetBoardAnalyticsAPIV1SchedulesBoardBoardConfigIDAnalyticsGetRequestTypedDict": ".get_board_analytics_api_v1_schedules_board_board_config_id_analytics_getop",
    "GetScheduleAnalyticsAPIV1SchedulesScheduleIDAnalyticsGetRequest": ".get_schedule_analytics_api_v1_schedules_schedule_id_analytics_getop",
    "GetScheduleAnalyticsAPIV1SchedulesScheduleIDAnalyticsGetRequestTypedDict": ".get_schedule_analytics_api_v1_schedules_schedule_id_analytics_getop",
    "GetScheduleAPIV1SchedulesScheduleIDGetRequest": ".get_schedule_api_v1_schedules_schedule_id_getop",
    "GetScheduleAPIV1SchedulesScheduleIDGetRequestTypedDict": ".get_schedule_api_v1_schedules_schedule_id_getop",
    "GetSchedulesAPIV1SchedulesGetRequest": ".get_schedules_api_v1_schedules_getop",
    "GetSchedulesAPIV1SchedulesGetRequestTypedDict": ".get_schedules_api_v1_schedules_getop",
    "GetWorkItemAPIV1WorkitemsWorkItemIDGetRequest": ".get_work_item_api_v1_workitems_work_item_id_getop",
    "GetWorkItemAPIV1WorkitemsWorkItemIDGetRequestTypedDict": ".get_work_item_api_v1_workitems_work_item_id_getop",
    "GetWorkItemsAPIV1WorkitemsGetRequest": ".get_work_items_api_v1_workitems_getop",
    "GetWorkItemsAPIV1WorkitemsGetRequestTypedDict": ".get_work_items_api_v1_workitems_getop",
    "LoginRequest": ".loginrequest",
    "LoginRequestTypedDict": ".loginrequest",
    "LoginResponse": ".loginresponse",
    "LoginResponseTypedDict": ".loginresponse",
    "ScheduleAnalytics": ".scheduleanalytics",
    "ScheduleAnalyticsTypedDict": ".scheduleanalytics",
    "ScheduleCreate": ".schedulecreate",
    "ScheduleCreateTypedDict": ".schedulecreate",
    "ScheduleResponse": ".scheduleresponse",
    "ScheduleResponseTypedDict": ".scheduleresponse",
    "ScheduleUpdate": ".scheduleupdate",
    "ScheduleUpdateTypedDict": ".scheduleupdate",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "SetSystemTimeAPIV1SystemTimePostRequest": ".set_system_time_api_v1_system_time_postop",
    "SetSystemTimeAPIV1SystemTimePostRequestTypedDict": ".set_system_time_api_v1_system_time_postop",
    "TaskCreate": ".taskcreate",
    "TaskCreateTypedDict": ".taskcreate",
    "TaskResponse": ".taskresponse",
    "TaskResponseTypedDict": ".taskresponse",
    "TaskUpdate": ".taskupdate",
    "TaskUpdateTypedDict": ".taskupdate",
    "UpdateScheduleAPIV1SchedulesScheduleIDPutRequest": ".update_schedule_api_v1_schedules_schedule_id_putop",
    "UpdateScheduleAPIV1SchedulesScheduleIDPutRequestTypedDict": ".update_schedule_api_v1_schedules_schedule_id_putop",
    "UpdateWorkItemAPIV1WorkitemsWorkItemIDPutRequest": ".update_work_item_api_v1_workitems_work_item_id_putop",
    "UpdateWorkItemAPIV1WorkitemsWorkItemIDPutRequestTypedDict": ".update_work_item_api_v1_workitems_work_item_id_putop",
    "UpdateWorkItemTaskAPIV1WorkitemsWorkItemIDTasksTaskIDPutRequest": ".update_work_item_task_api_v1_workitems_work_item_id_tasks_task_id_putop",
    "UpdateWorkItemTaskAPIV1WorkitemsWorkItemIDTasksTaskIDPutRequestTypedDict": ".update_work_item_task_api_v1_workitems_work_item_id_tasks_task_id_putop",
    "UserInfo": ".userinfo",
    "UserInfoTypedDict": ".userinfo",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
    "WorkItemCreate": ".workitemcreate",
    "WorkItemCreateTypedDict": ".workitemcreate",
    "WorkItemResponse": ".workitemresponse",
    "WorkItemResponseTypedDict": ".workitemresponse",
    "WorkItemUpdate": ".workitemupdate",
    "WorkItemUpdateTypedDict": ".workitemupdate",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)
