"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from typing_extensions import TypedDict


class AdvanceTimeResponseTypedDict(TypedDict):
    r"""Response model for advance_time_unit endpoint"""

    message: str
    r"""Success message"""
    advanced_schedules_count: int
    r"""Number of schedules that were advanced"""


class AdvanceTimeResponse(BaseModel):
    r"""Response model for advance_time_unit endpoint"""

    message: str
    r"""Success message"""

    advanced_schedules_count: int
    r"""Number of schedules that were advanced"""
