"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from typing import Dict
from typing_extensions import TypedDict


class BoardAnalyticsTypedDict(TypedDict):
    total_schedules: int
    status_distribution: Dict[str, int]
    zone_occupancy: Dict[str, int]
    capacity_utilization: Dict[str, float]


class BoardAnalytics(BaseModel):
    total_schedules: int

    status_distribution: Dict[str, int]

    zone_occupancy: Dict[str, int]

    capacity_utilization: Dict[str, float]
