"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from typing_extensions import TypedDict


class DbrAPIMembershipsUserInfoTypedDict(TypedDict):
    r"""Schema for user information in membership response"""

    id: str
    username: str
    email: str
    display_name: str
    active_status: bool


class DbrAPIMembershipsUserInfo(BaseModel):
    r"""Schema for user information in membership response"""

    id: str

    username: str

    email: str

    display_name: str

    active_status: bool
