"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from dbrsdk.utils import FieldMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class GetUsersAPIV1UsersGetRequestTypedDict(TypedDict):
    organization_id: str
    r"""Organization ID to filter users"""


class GetUsersAPIV1UsersGetRequest(BaseModel):
    organization_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Organization ID to filter users"""
