"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from dbrsdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class GetBoardAnalyticsAPIV1SchedulesBoardBoardConfigIDAnalyticsGetRequestTypedDict(
    TypedDict
):
    board_config_id: str
    organization_id: str
    r"""Organization ID to scope the request"""


class GetBoardAnalyticsAPIV1SchedulesBoardBoardConfigIDAnalyticsGetRequest(BaseModel):
    board_config_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    organization_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Organization ID to scope the request"""
