"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from dbrsdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class GetWorkItemAPIV1WorkitemsWorkItemIDGetRequestTypedDict(TypedDict):
    work_item_id: str
    organization_id: str
    r"""Organization ID to scope the request"""


class GetWorkItemAPIV1WorkitemsWorkItemIDGetRequest(BaseModel):
    work_item_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    organization_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Organization ID to scope the request"""
