"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from dbrsdk.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class GetWorkItemsAPIV1WorkitemsGetRequestTypedDict(TypedDict):
    organization_id: str
    r"""Organization ID to filter by"""
    collection_id: NotRequired[Nullable[str]]
    r"""Collection ID to filter by"""
    status: NotRequired[Nullable[List[str]]]
    r"""Status to filter by"""
    priority: NotRequired[Nullable[str]]
    r"""Priority to filter by"""
    sort: NotRequired[Nullable[str]]
    r"""Sort field"""


class GetWorkItemsAPIV1WorkitemsGetRequest(BaseModel):
    organization_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Organization ID to filter by"""

    collection_id: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Collection ID to filter by"""

    status: Annotated[
        OptionalNullable[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Status to filter by"""

    priority: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Priority to filter by"""

    sort: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Sort field"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["collection_id", "status", "priority", "sort"]
        nullable_fields = ["collection_id", "status", "priority", "sort"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
