"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class LoginResponseTypedDict(TypedDict):
    r"""Login response model"""

    access_token: str
    r"""JWT access token"""
    user: Dict[str, Any]
    r"""User information"""
    token_type: NotRequired[str]
    r"""Token type"""


class LoginResponse(BaseModel):
    r"""Login response model"""

    access_token: str
    r"""JWT access token"""

    user: Dict[str, Any]
    r"""User information"""

    token_type: Optional[str] = "bearer"
    r"""Token type"""
