"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from typing_extensions import TypedDict


class LoginRequestTypedDict(TypedDict):
    r"""Login request model"""

    username: str
    r"""Username or email address"""
    password: str
    r"""User password"""


class LoginRequest(BaseModel):
    r"""Login request model"""

    username: str
    r"""Username or email address"""

    password: str
    r"""User password"""
