"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from typing_extensions import TypedDict


class MembershipCreateTypedDict(TypedDict):
    r"""Schema for creating a new membership"""

    user_id: str
    r"""User ID to add to organization"""
    role_id: str
    r"""Role ID to assign to user"""


class MembershipCreate(BaseModel):
    r"""Schema for creating a new membership"""

    user_id: str
    r"""User ID to add to organization"""

    role_id: str
    r"""Role ID to assign to user"""
