"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class MembershipUpdateTypedDict(TypedDict):
    r"""Schema for updating a membership"""

    role_id: NotRequired[Nullable[str]]
    r"""Role ID to assign to user"""
    invitation_status: NotRequired[Nullable[str]]
    r"""Invitation status"""


class MembershipUpdate(BaseModel):
    r"""Schema for updating a membership"""

    role_id: OptionalNullable[str] = UNSET
    r"""Role ID to assign to user"""

    invitation_status: OptionalNullable[str] = UNSET
    r"""Invitation status"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["role_id", "invitation_status"]
        nullable_fields = ["role_id", "invitation_status"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
