"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from typing_extensions import TypedDict


class RoleInfoTypedDict(TypedDict):
    r"""Schema for role information in membership response"""

    id: str
    name: str
    description: str


class RoleInfo(BaseModel):
    r"""Schema for role information in membership response"""

    id: str

    name: str

    description: str
