"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ScheduleCreateTypedDict(TypedDict):
    organization_id: str
    r"""Organization ID"""
    board_config_id: str
    r"""Board configuration ID"""
    work_item_ids: List[str]
    r"""List of work item IDs"""
    timezone: NotRequired[str]
    r"""Timezone for schedule dates"""


class ScheduleCreate(BaseModel):
    organization_id: str
    r"""Organization ID"""

    board_config_id: str
    r"""Board configuration ID"""

    work_item_ids: List[str]
    r"""List of work item IDs"""

    timezone: Optional[str] = "UTC"
    r"""Timezone for schedule dates"""
