"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from typing import Any, Dict
from typing_extensions import TypedDict


class ScheduleAnalyticsTypedDict(TypedDict):
    work_item_count: int
    total_ccr_hours: float
    buffer_zone: str
    position_info: Dict[str, Any]
    throughput_metrics: Dict[str, Any]


class ScheduleAnalytics(BaseModel):
    work_item_count: int

    total_ccr_hours: float

    buffer_zone: str

    position_info: Dict[str, Any]

    throughput_metrics: Dict[str, Any]
