"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from dbrsdk.utils import FieldMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class SetSystemTimeAPIV1SystemTimePostRequestTypedDict(TypedDict):
    time_iso: str
    r"""ISO format datetime to set as system time"""


class SetSystemTimeAPIV1SystemTimePostRequest(BaseModel):
    time_iso: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""ISO format datetime to set as system time"""
