"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class TaskUpdateTypedDict(TypedDict):
    title: NotRequired[Nullable[str]]
    r"""Task title"""
    completed: NotRequired[Nullable[bool]]
    r"""Task completion status"""


class TaskUpdate(BaseModel):
    title: OptionalNullable[str] = UNSET
    r"""Task title"""

    completed: OptionalNullable[bool] = UNSET
    r"""Task completion status"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["title", "completed"]
        nullable_fields = ["title", "completed"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
