"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TaskCreateTypedDict(TypedDict):
    title: str
    r"""Task title"""
    completed: NotRequired[bool]
    r"""Task completion status"""


class TaskCreate(BaseModel):
    title: str
    r"""Task title"""

    completed: Optional[bool] = False
    r"""Task completion status"""
