"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .membershipupdate import MembershipUpdate, MembershipUpdateTypedDict
from dbrsdk.types import BaseModel
from dbrsdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateMembershipAPIV1OrganizationsOrgIDMembershipsUserIDPutRequestTypedDict(
    TypedDict
):
    org_id: str
    user_id: str
    membership_update: MembershipUpdateTypedDict


class UpdateMembershipAPIV1OrganizationsOrgIDMembershipsUserIDPutRequest(BaseModel):
    org_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    user_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    membership_update: Annotated[
        MembershipUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
