"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .userupdate import UserUpdate, UserUpdateTypedDict
from dbrsdk.types import BaseModel
from dbrsdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateUserAPIV1UsersUserIDPutRequestTypedDict(TypedDict):
    user_id: str
    user_update: UserUpdateTypedDict


class UpdateUserAPIV1UsersUserIDPutRequest(BaseModel):
    user_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    user_update: Annotated[
        UserUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
