"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .organizationupdate import OrganizationUpdate, OrganizationUpdateTypedDict
from dbrsdk.types import BaseModel
from dbrsdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateOrganizationAPIV1OrganizationsOrgIDPutRequestTypedDict(TypedDict):
    org_id: str
    organization_update: OrganizationUpdateTypedDict


class UpdateOrganizationAPIV1OrganizationsOrgIDPutRequest(BaseModel):
    org_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    organization_update: Annotated[
        OrganizationUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
