"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .collectionupdate import CollectionUpdate, CollectionUpdateTypedDict
from dbrsdk.types import BaseModel
from dbrsdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    RequestMetadata,
)
from typing_extensions import Annotated, TypedDict


class UpdateCollectionAPIV1CollectionsCollectionIDPutRequestTypedDict(TypedDict):
    collection_id: str
    organization_id: str
    r"""Organization ID to scope the request"""
    collection_update: CollectionUpdateTypedDict


class UpdateCollectionAPIV1CollectionsCollectionIDPutRequest(BaseModel):
    collection_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    organization_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Organization ID to scope the request"""

    collection_update: Annotated[
        CollectionUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
