"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workitemupdate import WorkItemUpdate, WorkItemUpdateTypedDict
from dbrsdk.types import BaseModel
from dbrsdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    RequestMetadata,
)
from typing_extensions import Annotated, TypedDict


class UpdateWorkItemAPIV1WorkitemsWorkItemIDPutRequestTypedDict(TypedDict):
    work_item_id: str
    organization_id: str
    r"""Organization ID to scope the request"""
    work_item_update: WorkItemUpdateTypedDict


class UpdateWorkItemAPIV1WorkitemsWorkItemIDPutRequest(BaseModel):
    work_item_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    organization_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Organization ID to scope the request"""

    work_item_update: Annotated[
        WorkItemUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
