"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .scheduleupdate import ScheduleUpdate, ScheduleUpdateTypedDict
from dbrsdk.types import BaseModel
from dbrsdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    RequestMetadata,
)
from typing_extensions import Annotated, TypedDict


class UpdateScheduleAPIV1SchedulesScheduleIDPutRequestTypedDict(TypedDict):
    schedule_id: str
    organization_id: str
    r"""Organization ID to scope the request"""
    schedule_update: ScheduleUpdateTypedDict


class UpdateScheduleAPIV1SchedulesScheduleIDPutRequest(BaseModel):
    schedule_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    organization_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Organization ID to scope the request"""

    schedule_update: Annotated[
        ScheduleUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
