"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .taskupdate import TaskUpdate, TaskUpdateTypedDict
from dbrsdk.types import BaseModel
from dbrsdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    RequestMetadata,
)
from typing_extensions import Annotated, TypedDict


class UpdateWorkItemTaskAPIV1WorkitemsWorkItemIDTasksTaskIDPutRequestTypedDict(
    TypedDict
):
    work_item_id: str
    task_id: int
    organization_id: str
    r"""Organization ID to scope the request"""
    task_update: TaskUpdateTypedDict


class UpdateWorkItemTaskAPIV1WorkitemsWorkItemIDTasksTaskIDPutRequest(BaseModel):
    work_item_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    task_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    organization_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Organization ID to scope the request"""

    task_update: Annotated[
        TaskUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
