"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UserCreateTypedDict(TypedDict):
    r"""Schema for creating a new user"""

    organization_id: str
    r"""Organization ID"""
    username: str
    r"""Username"""
    email: str
    r"""Email address"""
    display_name: str
    r"""Display name"""
    password: str
    r"""Password"""
    system_role_id: str
    r"""System role ID"""
    active_status: NotRequired[bool]
    r"""Active status"""


class UserCreate(BaseModel):
    r"""Schema for creating a new user"""

    organization_id: str
    r"""Organization ID"""

    username: str
    r"""Username"""

    email: str
    r"""Email address"""

    display_name: str
    r"""Display name"""

    password: str
    r"""Password"""

    system_role_id: str
    r"""System role ID"""

    active_status: Optional[bool] = True
    r"""Active status"""
