"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class UserUpdateTypedDict(TypedDict):
    r"""Schema for updating a user"""

    username: NotRequired[Nullable[str]]
    r"""Username"""
    email: NotRequired[Nullable[str]]
    r"""Email address"""
    display_name: NotRequired[Nullable[str]]
    r"""Display name"""
    system_role_id: NotRequired[Nullable[str]]
    r"""System role ID"""
    active_status: NotRequired[Nullable[bool]]
    r"""Active status"""


class UserUpdate(BaseModel):
    r"""Schema for updating a user"""

    username: OptionalNullable[str] = UNSET
    r"""Username"""

    email: OptionalNullable[str] = UNSET
    r"""Email address"""

    display_name: OptionalNullable[str] = UNSET
    r"""Display name"""

    system_role_id: OptionalNullable[str] = UNSET
    r"""System role ID"""

    active_status: OptionalNullable[bool] = UNSET
    r"""Active status"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "username",
            "email",
            "display_name",
            "system_role_id",
            "active_status",
        ]
        nullable_fields = [
            "username",
            "email",
            "display_name",
            "system_role_id",
            "active_status",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
