"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dbrsdk.types import BaseModel
from typing_extensions import TypedDict


class UserResponseTypedDict(TypedDict):
    r"""Schema for user response"""

    id: str
    username: str
    email: str
    display_name: str
    active_status: bool
    system_role_id: str
    created_date: str
    updated_date: str


class UserResponse(BaseModel):
    r"""Schema for user response"""

    id: str

    username: str

    email: str

    display_name: str

    active_status: bool

    system_role_id: str

    created_date: str

    updated_date: str
